backend = "glx";
use-damage = true;
vsync = true;
corner-radius = 0;

round-borders = 0;
round-borders-exclude = [
	"class_g = 'i3-frame'"
];

shadow = false
shadow-radius = 10;
shadow-opacity = 0.3;

fading = false;
fade-in-step = 0.04;
fade-out-step = 0.04;

animations = true;
animation-stiffness = 300.0;
animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-workspace-switch-in = "slide-down";
animation-for-workspace-switch-out = "zoom";



#blur-background = false;
#blur-method = "dual_kawase";
#blur-strength = 0;

