# vim: filetype=i3config


# Powermenu to lockscreen
bindsym $mod+p exec $powermenu

# Lock the screen
bindsym $mod+F1 exec --no-startup-id ~/.config/i3/scripts/lockman.sh

# Swap Wallpaper
bindsym $mod+Shift+g exec ~/.config/i3/scripts/bg_swap.sh

# Toggle i3bar (Show/Hide)
bindsym $mod+b bar mode toggle

# Restart/Close Polybar
#bindsym $mod+b exec --no-startup-id "killall -q polybar || ~/.config/polybar/launch.sh"
#bindsym $mod+Shift+b exec --no-startup-id "killall -q polybar; ~/.config/polybar/launch.sh"

# Opening a Terminal
bindsym $mod+Return exec --no-startup-id $terminal

# Closing Application
bindsym $mod+Shift+q kill
bindsym $mod+x kill

# Notification History
bindsym $mod+Shift+n exec dunstctl history-pop

#Screenshot
bindsym Print exec flameshot gui

# Lock-Screen
bindsym $mod+Ctrl+l exec i3-msg exit

# App Menu
bindsym $mod+d exec rofi -show drun

# Open Windows
bindsym $mod+Shift+p exec rofi -show window

# Switching Between Screens Using AutoRandr
bindsym $mod+F10 exec --no-startup-id autorandr --cycle

# yazi File Manager TUI
bindsym $mod+e exec --no-startup-id $terminal --class=float_big  -e ~/.cargo/bin/yazi

# imapal-nm TUI for WIFI
bindsym $mod+Shift+i exec --no-startup-id $terminal --class=float_small  -e ~/.cargo/bin/impala-nm

# wiremix TUI for volume
bindsym $mod+Shift+w exec --no-startup-id $terminal --class=float_small  -e wiremix

# bluetui TUI for bluetooth
bindsym $mod+Shift+m exec --no-startup-id $terminal --class=float_small -e ~/.cargo/bin/bluetui

# btop TUI for system resources
bindsym $mod+Escape exec --no-startup-id $terminal --class=float_large -e btop

# Open the default browser
bindsym $mod+o exec --no-startup-id brave-browser

# Audio Controls
# bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
# bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
# bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% && pkill -RTMIN+2 i3blocks
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% && pkill -RTMIN+2 i3blocks
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && pkill -RTMIN+2 i3blocks
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

# Brightness Controls
bindsym XF86MonBrightnessUp exec --no-startup-id "brightnessctl set +10% && xrandr --output HDMI-1 --brightness $(xrandr --verbose | grep -m 1 -A 5 'HDMI-1' | grep 'Brightness' | awk '{print ($2 + 0.1 > 1.0 ? 1.0 : $2 + 0.1)}') && pkill -RTMIN+3 i3blocks"
bindsym XF86MonBrightnessDown exec --no-startup-id "brightnessctl set 10%- && xrandr --output HDMI-1 --brightness $(xrandr --verbose | grep -m 1 -A 5 'HDMI-1' | grep 'Brightness' | awk '{print ($2 - 0.1 < 0.1 ? 0.1 : $2 - 0.1)}') && pkill -RTMIN+3 i3blocks"

# Restart i3
bindsym $mod+Shift+c restart
bindsym $mod+Shift+r restart

# exit i3 (logs you out of your X session)
bindsym $mod+Shift+z exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"



