# vim: filetype=i3config


# On First Startup
exec --no-startup-id dex-autostart --autostart --environment i3
exec --no-startup-id volumeicon
#exec --no-startup-id nm-applet
exec --no-startup-id xautolock -time 40 -locker "systemctl suspend"
exec --no-startup-id xss-lock --transfer-sleep-lock -- i2lock --nofork
exec --no-startup-id bluetoothctl power off > /dev/null 2>&1


# On Every Restart
exec_always --no-startup-id "killall nm-applet; killall blueman-applet"
exec_always --no-startup-id autorandr --change
#exec_always --no-startup-id "killall picom; picom -b --config ~/.config/picom/picom.conf"
exec_always --no-startup-id ~/.fehbg
#exec_always --no-startup-id ~/.config/polybar/launch.sh
#exec_always xrandr --output eDP-1 --off --output HDMI-2 --auto
exec_always --no-startup-id xset s 1800
exec_always --no-startup-id xset dpms 0 0 1800


