[FileDialog]
history=file:///home/moiz, file:///home/moiz/Anime/In Another World with my Smartphone/Season 01, file:///home/moiz/Anime/In Another World with my Smartphone/Season 02, file:///home/moiz/Documents/Mutawir/brand_website
lastVisited=file:///home/moiz/Documents/Mutawir/brand_website
qtVersion=6.11.1
shortcuts=file:, file:///home/moiz
sidebarWidth=95
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\x38\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\x2U\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0i\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
