# vim: filetype=swayconfig

# enable clipboard manager
exec wl-paste --watch cliphist store

# Brightness control
exec wl-gammarelay-rs

exec systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec systemctl --user start hyprland-session.targe

# Foot terminal server
#exec foot --server

# exec_always swaybg -i "$(cat /home/moiz/.background_wallpaper)" -m fill
exec systemctl --user start swaybg
exec systemctl --user start bar
exec systemctl --user start foot-server

### Idle configuration
# exec swayidle -w \
#         timeout 600 'swaylock -f -c 000000' \
#         timeout 1200 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
#         timeout 6000 'swaymsg "output * power on"; sleep 1; systemctl suspend' \
#         before-sleep 'swaylock -f -c 000000'

# enable auto tiling
exec_always autotiling -l 2

#exec_always "pkill waybar; waybar" 
exec_always "pkill kanshi; kanshi"

