# vim: filetype=swayconfig

include colors

# # Apply rounded corners to your bar (replace "waybar" with "swaybar" if using the default)
# layer_effects "panel" {
#     corner_radius 10
#     blur enable
#     shadows enable
# }
#


# Toggle swaybar (Show/Hide)
bindsym Mod4+c bar mode toggle

bar {
    # This uses the swaybar executable
    swaybar_command swaybar
    font pango: JetBrains Mono 12
    position top
    hidden_state hide
    modifier Mod4
    separator_symbol "" 
    #" ● "
    #height 30
    #gaps 8
    status_padding 0
    pango_markup enabled
    status_edge_padding 0
    workspace_buttons yes
    wrap_scroll yes
    # This tells swaybar where to get the text from
    #status_command i3status-rs ~/.config/i3status-rust/config.toml
    status_command i3blocks -c ~/.config/i3blocks/config

    # Styling to match your lean setup
    colors {
        # background #000000
        # statusline #FFFFFF
        # separator  #666666
        #
        # # class                 border     background text
        # focused_workspace       #000000    #000000    #FFFFFF  
        # active_workspace        #000000    #333333    #FFFFFF  
        # inactive_workspace      #000000    #000000    #707880  
        # urgent_workspace        #A54242    #A54242    #FFFFFF  

        # The bar background itself
        background $base
        # The color of the status text (CPU, RAM, Date)
        statusline $text
        # Separator color between blocks
        separator  $surface1

        # State             border    bg        text
        focused_workspace   $surface1 $blue     $base
        active_workspace    $surface1 $surface1 $text
        inactive_workspace  $base     $base     $subtext1
        urgent_workspace    $red      $red      $base
    }
}

