[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\n/home/moiz)
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\x3\0\0\0\x39\0\0\ap\0\0\x4(\0\0\x5\x5\0\0\0;\0\0\an\0\0\x4&\0\0\0\0\0\0\0\0\a\x80\0\0\x5\x5\0\0\0;\0\0\an\0\0\x4&)"

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(618 930)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[OpenDialog]
advanced=false
size=@Size(526 423)

[RecentsMRL]
list="https://rr1---sn-2uja-aixe7.googlevideo.com/videoplayback?expire=1776106180&ei=ZObcabC9BPO_mLAP_ZLjsA8&ip=103.134.1.58&id=o-AH_J7pDBF413IKALr2JOs32oz-aCdXZEGjIUg1Eh3roQ&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&cps=353&met=1776084580%2C&mh=am&mm=31%2C29&mn=sn-2uja-aixe7%2Csn-hgn7yn7s&ms=au%2Crdu&mv=m&mvi=1&pl=24&rms=au%2Cau&initcwndbps=546250&bui=AUUZDGK4BdXSaoN7viSjEV-0EEGRV7crhB2B3Q1EMjO2R91WMEqsvxEqaBXcIuRbMOAIVOlQseuc5nr4&spc=jlWavQtv1qAfOY8Wmh1PE1z67ukuBWYIqiJffb844XpKbzoO3tVV&vprv=1&svpuc=1&mime=video%2Fmp4&rqh=1&gir=yes&clen=971625046&ratebypass=yes&dur=11702.067&lmt=1768700154222607&mt=1776084087&fvip=5&fexp=51565116%2C51565682&c=ANDROID_VR&txp=5538534&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Crqh%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AHEqNM4wRAIgYlJwYpYAUEzY6e67RzS_-eyTIUUq3ka0tYv6mvEW0OwCIGXjB7zhdJmqIdLi58HFPsjX_z41T7RVKZOEFd2tc_Xe&lsparams=cps%2Cmet%2Cmh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Crms%2Cinitcwndbps&lsig=APaTxxMwRQIgDOeAXhceAJqsqYiYobR0fPYsl-0mADC3OKztuuEk2ysCIQCv12Edh96nJo-1odRFrdr4jNMJXCwCdwoyds5PQCniBg%3D%3D"
times=5469137
