[mgr]
ratio = [1, 3, 1]
show_hidden = false
show_symlink = true
sort_by = "natural"
sort_sensitive = false
sort_dir_first = true
mouse_events = ["click", "scroll"]
scrolloff = 10
linemode = "size"

[open]
rules = [
  # Folders
  { url = "*/", use = [
    "enter",
  ] },
  # Application Type
  { mime = "text/*", use = [
    "edit",
    "ask-cmd-block",
    "open",
  ] },
  { mime = "image/*", use = [
    "open",
  ] },
  { mime = "video/*", use = [
    "open",
    "vlc",
  ] },
  { mime = "application/pdf", use = [
    "zathura",
    "open",
    "ask-cmd-bg",
  ] },
  { url = "*.{cbz,cbr,cb7,cbt}", use = [
    "zathura",
    "open",
    "ask-cmd-bg",
  ] },
  { mime = "application/vnd.openxmlformats-officedocument*", use = [
    "open",
    "ask-cmd-bg",
  ] },
  { mime = "document/*", use = [
    "edit",
    "ask-cmd-block",
    "open",
  ] },
  # Catch all
  { mime = "*/*", use = [
    "open",
  ] },
  { url = "*", use = [
    "open",
  ] },
]

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Neovim", for = "unix" },
  { run = '$EDITOR "$@"', block = true, desc = "Editor", for = "unix" },
]
open = [{ run = 'xdg-open "$1"', desc = "Open", orphan = true, for = "linux" }]
copy-content = [{ run = 'cat "$1" | wl-copy', for = "linux" }]
ask-cmd-block = [
  { run = 'plugin open-with-cmd --args="-- block"', block = true, desc = "CMD (Blocking)", for = "unix" },
]
ask-cmd-bg = [
  { run = "plugin open-with-cmd", desc = "CMD (Background)", for = "unix" },
]
zathura = [
  { run = 'zathura "$@"', desc = "Zathura", orphan = true, for = "linux" },
]

[preview]
image_quality = 50
max_width = 320
max_height = 180
