# ~/.config/helix/config.toml

theme = "nord" # Set your preferred color theme natively

[editor]
line-numbers = "relative" # Relative line numbers for easy jumping
mouse = true              # Full mouse support in the terminal
cursorline = true         # Highlight the active row

[editor.cursor-shape]
insert = "line"            # Lean vertical bar in Insert Mode
normal = "block"          # Standard block cursor in Normal Mode

[editor.lsp]
display-messages = true   # Pop up code warnings/errors down in the status bar

