-------------------------
---- SOURCED CONFIGS ----
-------------------------
require("hyprland.autostart")
require("hyprland.visuals")
require("hyprland.keybinds")
require("hyprland.windows")
require("hyprland.workspace")
require("hyprland.rules")

------------------
---- MONITORS ----
------------------
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

-- -- Internal monitor as the origin (0,0)
-- hl.monitor({ output = "eDP-1", mode = "preferred", position = "0x0", scale = 1 })
--
-- -- External monitor positioned to the right of the laptop
-- hl.monitor({ output = "HDMI-A-1", mode = "preferred", position = "1920x0", scale = 1 })

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
	hl.exec_cmd(
		"dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE"
	)
end)

-------------------------------
---- GLOBAL CONFIGURATIONS ----
-------------------------------
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.config({
	autogenerated = false,

	xwayland = {
		enabled = false,
	},

	render = {
		expand_undersized_textures = false,
		cm_auto_hdr = false,
		cm_sdr_eotf = "default",
		direct_scanout = true,
	},

	-- env = {
	-- 	"XCURSOR_THEME,Bibata-Modern-Ice",
	-- 	"HYPRCURSOR_THEME,Bibata-Modern-Ice",
	-- 	"XCURSOR_SIZE,24",
	-- 	"HYPRCURSOR_SIZE,24",
	-- 	"QT_QPA_PLATFORMTHEME,qt6ct",
	-- 	-- "WLR_RENDERER_ALLOW_SOFTWARE,1",
	-- },

	misc = {
		force_default_wallpaper = false,
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		vrr = false,
		always_follow_on_dnd = false,
		animate_manual_resizes = false,
	},

	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		follow_mouse = 3,
		mouse_refocus = false,
		sensitivity = 0,

		touchpad = {
			natural_scroll = false,
		},
	},
	cursor = {
		no_hardware_cursors = false,
		inactive_timeout = 3,
	},
})

-------------------------
---- DEVICE SETTINGS ----
-------------------------
hl.device({
	name = "2.4g-mouse",
	sensitivity = 1.0,
	accel_profile = "adaptive",
}, {
	name = "alpsps/2-alps-dualpoint-touchpad",
	sensitivity = 0.2,
	natural_scroll = true,
})
