source = ~/.config/hypr/conf/visuals.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/window.conf
source = ~/.config/hypr/conf/workspace.conf
source = ~/.config/hypr/conf/rules.conf


# monitor=,preferred,auto,1
#
# # Internal monitor as the origin (0,0)
# monitor = eDP-1, preferred, 0x0, 1.333
#
# # External monitor positioned to the right of the laptop
# monitor = HDMI-A-1, preferred, auto-right, 1


xwayland {
  enabled = false
}

render {
    direct_scanout = true
}

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24



# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
    vrr = 0
}


input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
cursor {
    no_hardware_cursors = true
}


