
# Notification Daemon
#exec-once = dunst

# For AFK Detection
#exec-once = hypridle

# Terminal Server
#exec-once = foot --server

# Wallpaper Daemon
#exec-once = swaybg -i /home/moiz/.config/backgrounds/012.jpg -m fill

# Clipboard Daemon
exec-once = uwsm app -- wl-paste --watch cliphist store

#Brighntess Daemon
exec-once = uwsm app -- wl-gammarelay-rs

# Managing Multiple Monitors Daemon
#exec-once = kanshi

# Status Bar
#exec-once = uwsm app -- waybar

# Turn off Bluetooth on Start-up
exec-once = bluetoothctl power off

