exec-once = hyprpaper
exec-once = dunst
exec-once = hypridle
exec-once = foot --server
exec-once = swaybg -i /home/moiz/.config/backgrounds/012.jpg -m fill
exec-once = wl-paste --watch cliphist store
exec-once = wl-gammarelay-rs
exec-once = bluetoothctl power off
#exec = ~/.config/hypr/scripts/monitors.sh
exec-once = kanshi
exec-once = waybar
