# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrulev2 = float, class:(float_large)
windowrulev2 = size 1280 900, class:(float_large)
windowrulev2 = center, class:(float_large)


windowrulev2 = float, class:(float_big)
windowrulev2 = size 1100 800, class:(float_big)
windowrulev2 = center, class:(float_big)


windowrulev2 = float, class:(float_small)
windowrulev2 = size 900 600, class:(float_small)
windowrulev2 = center, class:(float_small)
