
# # Hide gaps when there is only one window
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
#
# windowrule = rounding 0, match:float 0, match:workspace w[tv1]
# windowrule = rounding 0, match:float 0, match:workspace f[1]

# Corrected syntax for Hyprland v0.51.1

# Workspace layout adjustments for non-floating windows
# windowrulev2 = border_size 0, floating:0, workspace:w[tv1]
# windowrulev2 = border_size 0, floating:0, workspace:f[1]

# Workspace layout adjustments for non-floating windows
# windowrulev2 = bordersize 0, floating:0, workspace:w[tv1]
# windowrulev2 = bordersize 0, floating:0, workspace:f
#
#
# # Large Floating Windows (e.g., 1280x900 pixels)
# windowrulev2 = float, class:^(float_large)$
# windowrulev2 = center, class:^(float_large)$
# windowrulev2 = size 1280 900, class:^(float_large)$
#
# # Big Floating Windows (e.g., 1100x800 pixels)
# windowrulev2 = float, class:^(float_big)$
# windowrulev2 = center, class:^(float_big)$
# windowrulev2 = size 1100 800, class:^(float_big)$
#
# # Small Floating Windows (e.g., 900x600 pixels)
# windowrulev2 = float, class:^(float_small)$
# windowrulev2 = center, class:^(float_small)$
# windowrulev2 = size 900 600, class:^(float_small)$
#
# # Thunar Rules
# windowrulev2 = float, class:^(thunar)$
# windowrulev2 = center, class:^(thunar)$
# windowrulev2 = size 1280 900, class:^(thunar)$
#

#Corrected new syntax: Uses 'float 0' instead of 'floating false'
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]

# Large Floating Windows (e.g., 1280x720 pixels)
windowrule = float on, center on, size 1280 900, match:class ^(float_large)$

# Big Floating Windows (e.g., 1024x768 pixels)
windowrule = float on, center on, size 1100 800, match:class ^(float_big)$

# Small Floating Windows (e.g., 640x480 pixels)
windowrule = float on, center on, size 900 600, match:class ^(float_small)$

windowrule = match:class ^(thunar)$, float on, center on, size 1280 900
