# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrule = float, class:(float_large)
windowrule = size 1280 900, class:(float_large)
windowrule = center, class:(float_large)


windowrule = float, class:(float_big)
windowrule = size 1100 800, class:(float_big)
windowrule = center, class:(float_big)


windowrule = float, class:(float_small)
windowrule = size 900 600, class:(float_small)
windowrule = center, class:(float_small)
