[colors] 
background = #302C3A 
;background-alt = #373B41FF
background-alt = #000000
foreground = #C5C8C6 
;primary = #F0C674 
secondary = #8ABEB7 
very_good = #00964E
good = #00CF6B
medium = #C2C738
bad = #C73838
very_bad = #B80000
alert = #A54242 
disabled = #707880 

;base = #373B41FF
base = #000000
lavender = #b4befe
sky = #89dceb
green = #a6e3a1
primary = #cba6f7

[bar/example] 
bottom = false

; If MONITOR is not set, it will default to your primary screen
monitor = ${env:MONITOR:}
width = 100% 
height = 24pt 
radius = 0; 
dpi = 100
background = ${colors.base}
foreground = ${colors.foreground} 
line-size = 1pt 
border-size = 0pt 
border-bottom-size = 0pt
border-color = #00000000
padding-left = 2
padding-right = 2
margin = 0
module-margin = 0
;separator-foreground = ${colors.disabled} 
font-0 = JetBrains Mono:size=12;3
font-1 = monospace:size=12;3
font-2 = JetBrainsMono Nerd Font:size=12;3
font-3 = Font Awesome 6 Free:size=12;3
font-4 = Roboto:size=12;3
font-5 = FontAwesome:size=12;3
font-6 = Helvetica:size=12;3
font-7 = Arial:size=12;3
font-8 = sans-serif:size=12;3
font-9 = JetBrains Mono:size=10;3

;modules-left = home wlan bluetooth mpd 
;modules-center = date
;modules-right = brightness pulseaudio memory cpu battery power

modules-left = home xworkspaces mpd 
modules-center = date
modules-right = brightness pulseaudio bluetooth wlan battery power

cursor-click = pointer 
cursor-scroll = ns-resize 
enable-ipc = true 
wm-restack = i3 

;override-redirect = true 

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/bluetooth.sh
interval = 1
click-right = bluetoothctl show | grep -q "Powered: yes" && bluetoothctl power off || bluetoothctl power on
click-left = kitty --class=float_small -e bluetui
format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0


[module/systray] 
type = internal/tray 
format-margin = 8pt 
tray-spacing = 16pt 


[module/battery]
type = internal/battery
full-at = 99
low-at = 20
battery = BAT0
adapter = AC
poll-interval = 5

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>
format-low = <label-low>

label-charging = %{F#00CF6B}%{F-} %percentage%%+
label-discharging = %{F#C2C738}%{F-} %percentage%%
label-full = %{F#00964E}%{F-}
label-low = %{F#B80000}LOW%{F-} %percentage%%

format-charging-background = ${colors.background-alt}
format-discharging-background = ${colors.background-alt}
format-full-background = ${colors.background-alt}
format-low-background = ${colors.background-alt}

format-charging-padding = 1
format-discharging-padding = 1
format-full-padding = 1
format-low-padding = 1

format-charging-margin = 0
format-discharging-margin = 0
format-full-margin = 0
format-low-margin = 0

[module/xworkspaces] 
type = internal/xworkspaces 
label-active =  " %name% "  
label-active-overline = #FFFFFF
;label-active-underline = #FFFFFF
;label-active-padding = 1
label-occupied = " %name% "
;label-occupied-padding = 1
label-urgent = " %name% "
label-urgent-background = ${colors.alert}
;label-urgent-padding = 1
label-empty = " %name% "
label-empty-foreground = ${colors.disabled}
;label-empty-padding = 1 


format-background = ${colors.background-alt}
format-active-background = ${colors.background-alt}
format-occupied-background = ${colors.background-alt}
format-empty-background = ${colors.background-alt}

;format-prefix = "|"
;format-suffix = "|"
format-padding = 0
format-margin = 0


[module/xwindow] 
type = internal/xwindow 
;label = %title:0:80:...% 
label = %{T10}%title:0:80:...%%{T-}
;label = %title:1:40:..%

format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0


[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}


[module/pulseaudio]
type = internal/pulseaudio
;format-volume-prefix = %{A1:kitty --class=float_small -e wiremix:} %{A}
format-volume-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %{A1:kitty --class=float_small -e wiremix:}%{A3:pactl set-sink-mute @DEFAULT_SINK@ toggle:}%{A}
label-muted = %{A1:kitty --class=float_small -e wiremix:}%{A3:pactl set-sink-mute @DEFAULT_SINK@ toggle:}%{A}%{A}
;label-muted = 
label-muted-foreground = ${colors.disabled}

format-muted-background = ${colors.background-alt}
format-volume-background = ${colors.background-alt}

format-muted-padding = 1
format-volume-padding = 1

format-muted-margin = 0
format-volume-margin = 0

use-ui-max = false


[module/memory]
type = internal/memory
interval = 2
label = %percentage_used:2%% 
label-foreground = ${colors.sky}
format = %{A1:ghostty -e htop:}<label>%{A}
format-prefix = %{A1:kitty --class=float_big -e btop:} %{A}
format-prefix-foreground = ${colors.sky}

format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0


[module/cpu]
type = internal/cpu
interval = 2
format = %{A1:ghostty -e htop:}<label>%{A}
label = %percentage:2%%
label-foreground = ${colors.sky}
format-prefix =  %{A1:kitty --class=float_big -e btop:} %{A}
format-prefix-foreground = ${colors.sky}

format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0


[network-base] 
type = internal/network
interval = 5 
format-connected = %{A1:kitty --class=float_small -e ~/.cargo/bin/impala-nm:}<label-connected>%{A}
format-disconnected = %{A1:kitty --class=float_small -e ~/.cargo/bin/impala-nm:}<label-disconnected>%{A}

format-connected-background = ${colors.background-alt}
format-connected-padding = 1
format-connected-margin = 0

format-disconnected-background = ${colors.background-alt}
format-disconnected-padding = 1
format-disconnected-margin = 0


[module/wlan]
inherit = network-base
interface-type = wireless 

;label-connected = %{F#F0C674}%{F-} %essid% 
;label-disconnected = %{F#F0C674}⚠%{F-} Disconnected

label-connected = %{F#F0C674}%{F-} 
label-disconnected = %{F#F0C674}⚠%{F-}

format-connected-background = ${colors.background-alt}
format-connected-padding = 1


[module/eth]
inherit = network-base
interface-type = wired 
label-connected = %{F#F0C674}%{F-} %local_ip%
label-disconnected = %{F#F0C674}⚠%{F-} Disconected


[module/date]
type = internal/date
interval = 1 

date = %H:%M 
date-alt = %Y-%m-%d %H:%M:%S

label = %date%

format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0


[settings]
screenchange-reload = true
pseudo-transparency = true


[module/notification-history]
type = custom/text
; Using a bell icon (if using Nerd Fonts) or just "NOTIFS"
content = "  "
content-foreground = ${colors.background-alt}

; Left click: Show the last notification again (History Pop)
click-left = dunstctl history-pop
; Middle click: Close all current notifications
click-middle = dunstctl close-all
; Right click: Clear the entire history
click-right = dunstctl history-clear


[module/brightness]
type = custom/text
;exec = brightnessctl -m | cut -d, -f4
;exec = echo ""
interval = 1
;format-prefix = ""
format-prefix-foreground = ${colors.primary}
format-foreground = ${colors.lavender}
label = ""
scroll-up = brightnessctl set +5% && xrandr --output HDMI-1 --brightness $(xrandr --verbose | grep -m 1 -A 5 "HDMI-1" | grep "Brightness" | awk '{print ($2 + 0.05 > 1.0 ? 1.0 : $2 + 0.05)}')
scroll-down = brightnessctl set 5%- && xrandr --output HDMI-1 --brightness $(xrandr --verbose | grep -m 1 -A 5 "HDMI-1" | grep "Brightness" | awk '{print ($2 - 0.05 < 0.1 ? 0.1 : $2 - 0.05)}')

format-background = ${colors.background-alt}
format-padding = 1
format-margin = 0

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
interval = 2
click-right = kitty --class float_small -e bluetui

format-online = <label-song> <icon-prev> <icon-pause> <icon-play> <icon-next> <label-time> 
format-online-background = ${colors.background-alt}
format-online-padding = 1

label-song = %{F#ffffff}%artist% - %title%%{F-}
label-song-maxlen = 25
label-song-ellipsis = true

label-time = %elapsed% / %total%
label-time-foreground = #b4befe

label-offline = ⚠ Disconnected

icon-play = 
icon-pause = 
icon-stop = 
icon-prev = 
icon-next = 

icon-play-foreground = ${colors.primary}
icon-pause-foreground = ${colors.primary}

[module/power]
type = custom/text
format = %{A1:~/.config/rofi/powermenu/powermenu.sh:}<label>%{A}
format-background = ${colors.background-alt}
format-prefix-foreground = ${colors.alert}
format-padding = 1
format-margin = 0

label = "⏻ "
label-foreground = ${colors.alert}

[module/home]
type = custom/text
format = %{A1: rofi -show drun -replace:}<label>%{A}
format-background = ${colors.background-alt}
;format-prefix-foreground = ${colors.alert}
format-padding = 1
format-margin = 0

label = ""
label-foreground = ${colors.lavender}


[bar/bottom]
bottom = true

; If MONITOR is not set, it will default to your primary screen
monitor = ${env:MONITOR:}
width = 100% 
height = 16pt 
radius = 0; 
dpi = 100
background = ${colors.base}
foreground = ${colors.foreground} 
line-size = 1pt 
border-size = 2pt 
border-bottom-size = 0pt
border-color = #000000
padding-left = 0
padding-right = 0
margin = 0
module-margin = 0
module-padding = 0
;font-0 = monospace:size=12;3 
font-0 = JetBrains Mono:size=12;4
font-2 = JetBrainsMono Nerd Font:size=12;4
;font-0 = Font Awesome 6 Free:size=10;3
;font-4 = Roboto:size=14;3
;font-5 = FontAwesome:size=14;3
;font-6 = Helvetica:size=14;3
;font-7 = Arial:size=14;3
;font-8 = sans-serif:size=14;3
font-1 = "Symbols Nerd Font Mono:size=12;2" 


modules-left = xworkspaces 
;modules-center = polywins
modules-right = xwindow 
cursor-click = pointer 
cursor-scroll = ns-resize 
enable-ipc = true 
wm-restack = i3 


[module/polywins]
type = custom/script
exec = ~/.config/polybar/polywins.sh
interval = 2
format = <label>
label = %output%
label-padding = 1


[module/window-dots]
type = custom/script
exec = ~/.config/polybar/polywins.sh --dots
interval = 1
; Click to trigger the "Name" view
click-left = polybar-msg action "#window-dots.module_hide" && polybar-msg action "#window-names.module_show"

[module/window-names]
type = custom/script
exec = ~/.config/polybar/polywins.sh --names
interval = 1
hidden = true
; Click to go back to dots
click-left = polybar-msg action "#window-names.module_hide" && polybar-msg action "#window-dots.module_show"


