# Use your Matugen variables here
$text = rgb(d9e2ff)
$entry_bg = rgba(00194411)
$entry_border = rgba(8f909955)

general {
    disable_loading = true
    hide_cursor = true
}

background {
    monitor =
    path = /home/moiz/.config/backgrounds/009.jpg
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 1 # 0 disables blurring
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $entry_border
    inner_color = $entry_bg
    font_color = $text
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = Welcome, $USER
    color = $text
    font_size = 25
    font_family = Google Sans Flex Medium
    position = 0, 80
    halign = center
    valign = center
}
